service: stone-challenge
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}

  environment:
    NODE_ENV: "${self:provider.stage}"
    SERVICE: "${self:service}"
    MONGODB_URI: "mongodb://localhost:27017"
    MONGODB_DATABASE: "stone"
    COUNT_API_URL: "https://api.countapi.xyz"
    COUNT_API_NAMESPACE: "www.ton.com.br"
    COUNT_API_INDEX: "huehue"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  excludeDevDependencies: true

functions:
  handler:
    handler: src/index.handler
    events:
      - http:
          path: /counter
          method: post
          cors: true
      - http:
          path: /counter
          method: get
          cors: true
